import unittest
import numpy as np
import group
import linear_prog
import numeric
from perturbed_lp import PerturbedLP, PinftyError
from linear_prog import LP, Sign, ColKind, RowKind
from typing import List, Tuple, Any

class TestPerturbedLP(unittest.TestCase):
    """
    Test suite for the PerturbedLP class.
    
    This class verifies that the perturbation logic for Phase I and Phase II
    linear programs is implemented correctly, following the structure
    of the original OCaml code.
    """

    def setUp(self):
        """
        Set up a common environment for all tests.
        This method runs before each test function.
        """
        # 1. Initialize the numeric and group modules
        # We use Max-Plus algebra for this test case.
        Num = numeric.TropicalNumericMaxPlus()
        self.G = group.GroupFromNumeric(Num)
        
        # 2. Define a simple Linear Program to be used as input for perturbation
        # LP: 2 variables (x0, x1), 2 inequalities
        def var_names(i):
            return ["x", "y"][i]
        
        # Objective: maximize 5*x0 + 10*x1  (in tropical sense)

        objective: List[Tuple[linear_prog.ColIndex, linear_prog.Sign, Any]] = [
            ((linear_prog.ColKind.VAR, 0), linear_prog.Sign.POS, 5.0),
            ((linear_prog.ColKind.VAR, 1), linear_prog.Sign.POS, 10.0)
        ]
        
        # Inequalities:
        # 0: x0 + 2 <= x1 + 3  =>  x0 + 2 - (x1 + 3) <= 0
        # 1: x1 + 8 <= 15      =>  x1 + 8 - 15 <= 0
        ineqs = [
            [
                ((linear_prog.ColKind.VAR, 0), linear_prog.Sign.NEG, 2.0),
                ((linear_prog.ColKind.VAR, 1), linear_prog.Sign.POS, 3.0),
            ],
            [
                ((linear_prog.ColKind.VAR, 1), linear_prog.Sign.NEG, 8.0),
                ((linear_prog.ColKind.AFFINE, None), linear_prog.Sign.POS, 15.0),
            ]
        ]

        LP_mod = linear_prog.LinearProg(self.G)
        self.lp = LP_mod.init(var_names, nb_var= 2, objective=objective, ineqs=ineqs)
        
        # 3. Instantiate the class we want to test
        self.pert_lp = PerturbedLP(LP_mod)

    def test_initialization(self):
        """
        Test that the PerturbedLP class is initialized correctly.
        """
        # The original group G should be preserved
        self.assertIs(self.pert_lp.G, self.G)
        
        # Check that the perturbation groups F and H are correctly instantiated
        self.assertIsInstance(self.pert_lp.F, group.IntGroup)
        self.assertIsInstance(self.pert_lp.H, group.CartesianPowerSparse)
        
        # The perturbed group PertG should be a CartesianProduct
        self.assertIsInstance(self.pert_lp.PertG, group.CartesianProduct)
        
        # The internal LP factory should use the new perturbed group
        self.assertIs(self.pert_lp.LP_pert_mod.G, self.pert_lp.PertG)
        print("Test Initialization: PASSED")

    def test_project_method(self):
        """
        Test the projection from the perturbed group back to the original group G.
        """
        # Case 1: f > 0, should raise PinftyError
        fgh_p_inf = self.pert_lp._from_entries(1, 10.0, [])
        with self.assertRaises(PinftyError):
            self.pert_lp.project(fgh_p_inf)

        # Case 2: f == 0, should return g
        fgh_zero = self.pert_lp._from_entries(0, 25.0, [(1, 1)])
        self.assertEqual(self.pert_lp.project(fgh_zero), 25.0)

        # Case 3: f < 0, should return None (representing -infinity)
        fgh_n_inf = self.pert_lp._from_entries(-1, 50.0, [])
        self.assertIsNone(self.pert_lp.project(fgh_n_inf))
        print("Test Project Method: PASSED")

    def test_row_indices(self):
        """
        Test the calculation of special row indices for Phase I and Phase II.
        """
        expected_index = self.lp.dim() + self.lp.nb_ineq()
        
        self.assertEqual(self.pert_lp.phaseII_upperbound_row(self.lp), expected_index)
        self.assertEqual(self.pert_lp.phaseI_infeasibility_var_lower_bound_row(self.lp), expected_index)
        print("Test Row Indices: PASSED")

    def test_phaseI_output_structure(self):
        """
        Test the structure of the LP and basic point generated by phaseI.
        """
        phaseI_lp, initial_point = self.pert_lp.phaseI(self.lp)
        
        # The number of variables should be dim + 1 (for the infeasibility variable)
        self.assertEqual(phaseI_lp.dim(), self.lp.dim() + 1) # 2 + 1 = 3
        
        # The number of inequalities should be nb_ineq + dim + 2
        # (original ineqs + lower bounds + infeasibility LB + infinity plane)
        self.assertEqual(phaseI_lp.nb_ineq(), self.lp.nb_ineq() + self.lp.dim() + 2) # 2 + 2 + 2 = 6

        # The initial basic point should have a value for each variable
        self.assertEqual(initial_point.shape, (self.lp.dim() + 1,))
        
        # The objective function should contain exactly one term for the infeasibility variable
        self.assertEqual(len(phaseI_lp.objective), 1)
        obj_var_idx = phaseI_lp.objective[0][0][1]
        self.assertEqual(obj_var_idx, self.lp.dim()) # Should be the last variable
        print("Test Phase I Output Structure: PASSED")

    def test_phaseII_output_structure(self):
        """
        Test the structure of the LP generated by phaseII.
        """
        phaseII_lp = self.pert_lp.phaseII(self.lp)

        # The number of variables should be the same as the original LP
        self.assertEqual(phaseII_lp.dim(), self.lp.dim()) # 2
        
        # The number of inequalities should be nb_ineq + dim + 1
        # (original ineqs + lower bounds + infinity plane)
        self.assertEqual(phaseII_lp.nb_ineq(), self.lp.nb_ineq() + self.lp.dim() + 1) # 2 + 2 + 1 = 5
        
        # The objective function should be a perturbed version of the original
        original_obj = self.lp.get_row((RowKind.OBJECTIVE, None))
        perturbed_obj = phaseII_lp.get_row((RowKind.OBJECTIVE, None))
        self.assertEqual(len(perturbed_obj), len(original_obj))
        
        # Check that the 'g' component of the perturbed objective matches the original
        for i in range(len(original_obj)):
            original_g = original_obj[i][2]
            perturbed_g = self.pert_lp._second(perturbed_obj[i][2])
            self.assertEqual(original_g, perturbed_g)
        print("Test Phase II Output Structure: PASSED")


if __name__ == '__main__':
    unittest.main()